### ISSUE TITLE
tree-sitter-cpp crashes with munmap_chunk() when parsing with specific input

### ISSUE THREAD

**Issue by taoky** [tree-sitter/tree-sitter-cpp#175]
I'm testing tree-sitter-cpp with latest commit `f40125503642845492d87fa56ece3ed26a4ef4db` and rust binding, and I found that it will crash with `munmap_chunk(): invalid pointer` with a strange file as input :(.

Reproduce:

```rust
use std::{fs::File, io::Read};

use tree_sitter::{Parser, Language};

extern "C" { fn tree_sitter_cpp() -> Language; }

fn main() {
    let mut parser = Parser::new();
    parser.set_language(unsafe {tree_sitter_cpp()}).unwrap();

    let mut buffer = Vec::new();
    File::open("example.c").unwrap().read_to_end(&mut buffer).unwrap();

    let tree = parser.parse(buffer, None).unwrap();
    println!("{:?}", tree);
}
```

build.rs:

```rust
use std::{env, path::PathBuf};

fn main() {
    let libdir =
        PathBuf::from(env::var("TSCPP_DIR").unwrap_or_else(|_| "../tree-sitter-cpp/".to_string()))
            .join("src");

    cc::Build::new()
        .include(&libdir)
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-but-set-variable")
        .flag_if_supported("-Wno-trigraphs")
        .file(libdir.join("parser.c"))
        .compile("cpp-parser");

    cc::Build::new()
        .cpp(true)
        .include(&libdir)
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-but-set-variable")
        .file(libdir.join("scanner.cc"))
        .compile("cpp-scanner");
}
```

with "example.c" downloaded from <https://github.com/MeshSr/u-boot-meshsr/raw/9c39146b76cfea715456e3a1df5ece394975b01e/board/esd/ar405/fpgadata_xl30.c>.

```
> cargo run                                                                                              
   Compiling ts-crash v0.1.0 (/home/username/tmp/ts-crash)
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/ts-crash`
{Tree {Node ERROR (1, 0) - (777, 0)}}
munmap_chunk(): invalid pointer
fish: Job 1, 'cargo run' terminated by signal SIGABRT (Abort)
```

`coredumpctl gdb` shows following backtrace:

```
>>> bt
#0  0x00007f931a0af4dc in ?? () from /usr/lib/libc.so.6
#1  0x00007f931a05f998 in raise () from /usr/lib/libc.so.6
#2  0x00007f931a04953d in abort () from /usr/lib/libc.so.6
#3  0x00007f931a0a367e in ?? () from /usr/lib/libc.so.6
#4  0x00007f931a0b926c in ?? () from /usr/lib/libc.so.6
#5  0x00007f931a0b94fc in ?? () from /usr/lib/libc.so.6
#6  0x00007f931a0bda7a in free () from /usr/lib/libc.so.6
#7  0x0000556ea80ecb7a in ts_subtree_release (pool=0x7ffef445d970, self=...) at src/./subtree.c:609
#8  0x0000556ea80ed386 in ts_tree_delete (self=0x556ea925e6f0) at src/./tree.c:31
#9  0x0000556ea80da902 in tree_sitter::{impl#6}::drop (self=0x7ffef445da68) at /home/username/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tree-sitter-0.20.9/binding_rust/lib.rs:776
#10 0x0000556ea80c5a0b in core::ptr::drop_in_place<tree_sitter::Tree> () at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ptr/mod.rs:486
#11 0x0000556ea80c521a in ts_crash::main () at src/main.rs:16
```

It seems that it crashes when destructing the tree. I'm not sure whether this bug belongs to tree-sitter-cpp or tree-sitter itself. Please help me transfer the issue if I posted this in the wrong place.

**Comment by maxbrunsfeld** [comment]
Thanks so much for the report! This was a bug in the Tree-sitter library. It's fixed on Tree-sitter's master branch. I'll release a new version of the Tree-sitter crate soon.
